### ISSUE TITLE
Does this still works under their new API

### ISSUE THREAD

**Issue by eyalish** [LandRover/postil-status#2]
@LandRover Do you know if it works for their latest website?
Regards

**Comment by LandRover** [comment]
Heya,
No, it doesnt work anymore, due to few issues:

- CSRF token add, will result in 2 requests for each ID check
- Application firewall, seems to be blocking X reqs/min. (proxy might be required on scale)

**Comment by LandRover** [comment]
Fixed if you still need it. Version +0.2.0 @npm
